商品一覧、詳細機能作成
keita1899/rails_ec pull request #1
Opened 2023-07-27 12:19 UTC by keita1899

## 課題のリンク
商品一覧画面
https://shrouded-bayou-25816-d608a3e2d0c5.herokuapp.com/products

商品詳細画面
https://shrouded-bayou-25816-d608a3e2d0c5.herokuapp.com/products/1

## やったこと
- ダミーの商品データ作成
- 商品一覧画面、機能の作成
- 商品詳細画面、機能の作成
- Herokuにデプロイ

## 動作確認方法
1. git clone https://github.com/keita1899/rails_ec.git
2. docker compose build
3. docker compose up -d

## その他
- 商品コードの仕様がわからなかったので、3桁のランダムの英数字を3つ組み合わせたものにしました。
- とりあえず画面に表示するために割引価格のカラムを作ったのですが、割引価格はデータベースに保存すべきなのでしょうか？　個人的にはどれくらいの割引かによって変わってしまうので保存しなくていいと考えてます。

2023-07-27 13:20 UTC, keita1899 commented
よろしくお願いいたします！

2023-07-28 04:21 UTC, ihatov08 commented
>とりあえず画面に表示するために割引価格のカラムを作ったのですが、割引価格はデータベースに保存すべきなのでしょうか？　個人的にはどれくらいの割引かによって変わってしまうので保存しなくていいと考えてます。

今回は保存しない方式で問題ないです！

2023-07-28 04:23 UTC, ihatov08 requested changes
> ※以下で使用するテンプレートは英語表記ですが、日本語表記や並びに変更してください。

こちら対応お願いします！

2023-07-28 11:57 UTC, keita1899 commented
> > とりあえず画面に表示するために割引価格のカラムを作ったのですが、割引価格はデータベースに保存すべきなのでしょうか？　個人的にはどれくらいの割引かによって変わってしまうので保存しなくていいと考えてます。
> 
> 今回は保存しない方式で問題ないです！

かしこまりました！

2023-07-28 12:03 UTC, keita1899 commented
> > ※以下で使用するテンプレートは英語表記ですが、日本語表記や並びに変更してください。
> 
> こちら対応お願いします！

日本語表記の変更見落としてました、申し訳ありません。

ヘッダーのナビゲーションやサイトのメインの「Shop in style」などはそのままでよろしいでしょうか？

2023-07-30 12:58 UTC, ihatov08 commented
> > > ※以下で使用するテンプレートは英語表記ですが、日本語表記や並びに変更してください。
> > 
> > 
> > こちら対応お願いします！
> 
> 日本語表記の変更見落としてました、申し訳ありません。
> 
> ヘッダーのナビゲーションやサイトのメインの「Shop in style」などはそのままでよろしいでしょうか？

そのあたりはそのままでもよいです！

2023-07-31 01:54 UTC, keita1899 commented
> > > > ※以下で使用するテンプレートは英語表記ですが、日本語表記や並びに変更してください。
> > > 
> > > 
> > > こちら対応お願いします！
> > 
> > 
> > 日本語表記の変更見落としてました、申し訳ありません。
> > ヘッダーのナビゲーションやサイトのメインの「Shop in style」などはそのままでよろしいでしょうか？
> 
> そのあたりはそのままでもよいです！

かしこまりました！

2023-08-07 11:38 UTC, keita1899 commented
よろしくお願いいたします！

2023-08-07 11:43 UTC, keita1899 commented
## 課題のリンク
商品一覧画面
https://shrouded-bayou-25816-d608a3e2d0c5.herokuapp.com/products

商品詳細画面
https://shrouded-bayou-25816-d608a3e2d0c5.herokuapp.com/products/1

## やったこと
- 日本語化

## 動作確認方法
1. git clone https://github.com/keita1899/rails_ec.git
2. docker compose build
3. docker compose up -d

## その他
- 初期状態で使えることを知らずに変にいじってしまったので元に戻しました。



よろしくお願いいたします！

2023-08-10 00:07 UTC, ihatov08 commented
> とりあえず画面に表示するために割引価格のカラムを作ったのですが、割引価格はデータベースに保存すべきなのでしょうか？　個人的にはどれくらいの割引かによって変わってしまうので保存しなくていいと考えてます。

時と場合によるので(割引率で割引したいのか、固定価格で割引したいのかなど）
一概には言えないですね。今回は保存しない形でよいと思います。

2023-08-10 00:09 UTC, ihatov08 requested changes
![image](https://github.com/keita1899/rails_ec/assets/14024165/6ffd2c85-4589-49b2-995a-5680ad5e35bf)

まだドル表記や小数点以下が表示されていて、日本語表記になっていないので修正お願いします！

2023-08-10 09:55 UTC, keita1899 commented
何度も同じ部分を修正できてなくて申し訳ありません。

日本語表記に修正いたしました。

よろしくお願いいたします！

2023-08-13 00:22 UTC, ihatov08 approved these changes
確認しました、LGTMです！

2023-08-13 07:14 UTC, keita1899 commented
ありがとうございます！

2023-08-13 07:14 UTC, merged